// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjdJsDA0NzvLMn3YrlMcoXO0FapZs_G6w',
    appId: '1:241296984676:web:79bbdd73466210e1f8ed71',
    messagingSenderId: '241296984676',
    projectId: 'fingerprint-app-2026',
    authDomain: 'fingerprint-app-2026.firebaseapp.com',
    storageBucket: 'fingerprint-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdchovY-bRndxubL7CBaR645YffFSmpg',
    appId: '1:241296984676:android:ea44be49fc89ffd2f8ed71',
    messagingSenderId: '241296984676',
    projectId: 'fingerprint-app-2026',
    storageBucket: 'fingerprint-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATjEPPsAKgEWneHxmeSoDmWybYwIiT8ZA',
    appId: '1:241296984676:ios:284c3664f751dee3f8ed71',
    messagingSenderId: '241296984676',
    projectId: 'fingerprint-app-2026',
    storageBucket: 'fingerprint-app-2026.firebasestorage.app',
    iosBundleId: 'com.fingerprintapp.fingerprintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATjEPPsAKgEWneHxmeSoDmWybYwIiT8ZA',
    appId: '1:241296984676:ios:284c3664f751dee3f8ed71',
    messagingSenderId: '241296984676',
    projectId: 'fingerprint-app-2026',
    storageBucket: 'fingerprint-app-2026.firebasestorage.app',
    iosBundleId: 'com.fingerprintapp.fingerprintApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjdJsDA0NzvLMn3YrlMcoXO0FapZs_G6w',
    appId: '1:241296984676:web:21d7f50b77efa4a8f8ed71',
    messagingSenderId: '241296984676',
    projectId: 'fingerprint-app-2026',
    authDomain: 'fingerprint-app-2026.firebaseapp.com',
    storageBucket: 'fingerprint-app-2026.firebasestorage.app',
  );
}
